name: Lint Dockerfile
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          ignore: DL3048,DL3025,DL3018
